[package]
name = "helper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
serde_json = "1.0.89"
swc_core = { version = "0.59.*", features = [ "ecma_plugin_transform", "ecma_ast", "common"] }
