[package]
name = "kaze-style-swc-plugin-pre-transform"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_json = "1.0.89"
swc_core = { version = "0.44.*", features = ["plugin_transform"] }
