name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: 'yarn'
      - name: setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install wasm target
        run: rustup target add wasm32-wasi
      - name: install
        run: yarn install
      - name: build packages
        run: yarn build:packages
      - name: code check
        run: yarn code:check
      - name: test
        run: yarn test
      - name: release
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
