name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2.2.2
        name: setup pnpm
        with:
          version: 7
          run_install: false
      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.2
      - name: install dependencies
        run: pnpm install
      - name: build packages
        run: pnpm build:packages
      - name: test run
        run: pnpm test
